angular.module('milsApp')
  .factory('countries', function() {
   return [
    {
      "countryName":"AFGHANISTAN",
      "countryIso":"AF"
    },
    {
      "countryName":"ÅLAND ISLANDS",
      "countryIso":"AX"
    },
    {
      "countryName":"ALBANIA",
      "countryIso":"AL"
    },
    {
      "countryName":"ALGERIA",
      "countryIso":"DZ"
    },
    {
      "countryName":"AMERICAN SAMOA",
      "countryIso":"AS"
    },
    {
      "countryName":"ANDORRA",
      "countryIso":"AD"
    },
    {
      "countryName":"ANGOLA",
      "countryIso":"AO"
    },
    {
      "countryName":"ANGUILLA",
      "countryIso":"AI"
    },
    {
      "countryName":"ANTARCTICA",
      "countryIso":"AQ"
    },
    {
      "countryName":"ANTIGUA AND BARBUDA",
      "countryIso":"AG"
    },
    {
      "countryName":"ARGENTINA",
      "countryIso":"AR"
    },
    {
      "countryName":"ARMENIA",
      "countryIso":"AM"
    },
    {
      "countryName":"ARUBA",
      "countryIso":"AW"
    },
    {
      "countryName":"AUSTRALIA",
      "countryIso":"AU"
    },
    {
      "countryName":"AUSTRIA",
      "countryIso":"AT"
    },
    {
      "countryName":"AZERBAIJAN",
      "countryIso":"AZ"
    },
    {
      "countryName":"BAHAMAS",
      "countryIso":"BS"
    },
    {
      "countryName":"BAHRAIN",
      "countryIso":"BH"
    },
    {
      "countryName":"BANGLADESH",
      "countryIso":"BD"
    },
    {
      "countryName":"BARBADOS",
      "countryIso":"BB"
    },
    {
      "countryName":"BELARUS",
      "countryIso":"BY"
    },
    {
      "countryName":"BELGIUM",
      "countryIso":"BE"
    },
    {
      "countryName":"BELIZE",
      "countryIso":"BZ"
    },
    {
      "countryName":"BENIN",
      "countryIso":"BJ"
    },
    {
      "countryName":"BERMUDA",
      "countryIso":"BM"
    },
    {
      "countryName":"BHUTAN",
      "countryIso":"BT"
    },
    {
      "countryName":"BOLIVIA, PLURINATIONAL STATE OF",
      "countryIso":"BO"
    },
    {
      "countryName":"BONAIRE, SINT EUSTATIUS AND SABA",
      "countryIso":"BQ"
    },
    {
      "countryName":"BOSNIA AND HERZEGOVINA",
      "countryIso":"BA"
    },
    {
      "countryName":"BOTSWANA",
      "countryIso":"BW"
    },
    {
      "countryName":"BOUVET ISLAND",
      "countryIso":"BV"
    },
    {
      "countryName":"BRAZIL",
      "countryIso":"BR"
    },
    {
      "countryName":"BRITISH INDIAN OCEAN TERRITORY",
      "countryIso":"IO"
    },
    {
      "countryName":"BRUNEI DARUSSALAM",
      "countryIso":"BN"
    },
    {
      "countryName":"BULGARIA",
      "countryIso":"BG"
    },
    {
      "countryName":"BURKINA FASO",
      "countryIso":"BF"
    },
    {
      "countryName":"BURUNDI",
      "countryIso":"BI"
    },
    {
      "countryName":"CAMBODIA",
      "countryIso":"KH"
    },
    {
      "countryName":"CAMEROON",
      "countryIso":"CM"
    },
    {
      "countryName":"CANADA",
      "countryIso":"CA"
    },
    {
      "countryName":"CAPE VERDE",
      "countryIso":"CV"
    },
    {
      "countryName":"CAYMAN ISLANDS",
      "countryIso":"KY"
    },
    {
      "countryName":"CENTRAL AFRICAN REPUBLIC",
      "countryIso":"CF"
    },
    {
      "countryName":"CHAD",
      "countryIso":"TD"
    },
    {
      "countryName":"CHILE",
      "countryIso":"CL"
    },
    {
      "countryName":"CHINA",
      "countryIso":"CN"
    },
    {
      "countryName":"CHRISTMAS ISLAND",
      "countryIso":"CX"
    },
    {
      "countryName":"COCOS (KEELING) ISLANDS",
      "countryIso":"CC"
    },
    {
      "countryName":"COLOMBIA",
      "countryIso":"CO"
    },
    {
      "countryName":"COMOROS",
      "countryIso":"KM"
    },
    {
      "countryName":"CONGO",
      "countryIso":"CG"
    },
    {
      "countryName":"CONGO, THE DEMOCRATIC REPUBLIC OF THE",
      "countryIso":"CD"
    },
    {
      "countryName":"COOK ISLANDS",
      "countryIso":"CK"
    },
    {
      "countryName":"COSTA RICA",
      "countryIso":"CR"
    },
    {
      "countryName":"CÔTE D'IVOIRE",
      "countryIso":"CI"
    },
    {
      "countryName":"CROATIA",
      "countryIso":"HR"
    },
    {
      "countryName":"CUBA",
      "countryIso":"CU"
    },
    {
      "countryName":"CURAÇAO",
      "countryIso":"CW"
    },
    {
      "countryName":"CYPRUS",
      "countryIso":"CY"
    },
    {
      "countryName":"CZECH REPUBLIC",
      "countryIso":"CZ"
    },
    {
      "countryName":"DENMARK",
      "countryIso":"DK"
    },
    {
      "countryName":"DJIBOUTI",
      "countryIso":"DJ"
    },
    {
      "countryName":"DOMINICA",
      "countryIso":"DM"
    },
    {
      "countryName":"DOMINICAN REPUBLIC",
      "countryIso":"DO"
    },
    {
      "countryName":"ECUADOR",
      "countryIso":"EC"
    },
    {
      "countryName":"EGYPT",
      "countryIso":"EG"
    },
    {
      "countryName":"EL SALVADOR",
      "countryIso":"SV"
    },
    {
      "countryName":"EQUATORIAL GUINEA",
      "countryIso":"GQ"
    },
    {
      "countryName":"ERITREA",
      "countryIso":"ER"
    },
    {
      "countryName":"ESTONIA",
      "countryIso":"EE"
    },
    {
      "countryName":"ETHIOPIA",
      "countryIso":"ET"
    },
    {
      "countryName":"FALKLAND ISLANDS (MALVINAS)",
      "countryIso":"FK"
    },
    {
      "countryName":"FAROE ISLANDS",
      "countryIso":"FO"
    },
    {
      "countryName":"FIJI",
      "countryIso":"FJ"
    },
    {
      "countryName":"FINLAND",
      "countryIso":"FI"
    },
    {
      "countryName":"FRANCE",
      "countryIso":"FR"
    },
    {
      "countryName":"FRENCH GUIANA",
      "countryIso":"GF"
    },
    {
      "countryName":"FRENCH POLYNESIA",
      "countryIso":"PF"
    },
    {
      "countryName":"FRENCH SOUTHERN TERRITORIES",
      "countryIso":"TF"
    },
    {
      "countryName":"GABON",
      "countryIso":"GA"
    },
    {
      "countryName":"GAMBIA",
      "countryIso":"GM"
    },
    {
      "countryName":"GEORGIA",
      "countryIso":"GE"
    },
    {
      "countryName":"GERMANY",
      "countryIso":"DE"
    },
    {
      "countryName":"GHANA",
      "countryIso":"GH"
    },
    {
      "countryName":"GIBRALTAR",
      "countryIso":"GI"
    },
    {
      "countryName":"GREECE",
      "countryIso":"GR"
    },
    {
      "countryName":"GREENLAND",
      "countryIso":"GL"
    },
    {
      "countryName":"GRENADA",
      "countryIso":"GD"
    },
    {
      "countryName":"GUADELOUPE",
      "countryIso":"GP"
    },
    {
      "countryName":"GUAM",
      "countryIso":"GU"
    },
    {
      "countryName":"GUATEMALA",
      "countryIso":"GT"
    },
    {
      "countryName":"GUERNSEY",
      "countryIso":"GG"
    },
    {
      "countryName":"GUINEA",
      "countryIso":"GN"
    },
    {
      "countryName":"GUINEA-BISSAU",
      "countryIso":"GW"
    },
    {
      "countryName":"GUYANA",
      "countryIso":"GY"
    },
    {
      "countryName":"HAITI",
      "countryIso":"HT"
    },
    {
      "countryName":"HEARD ISLAND AND MCDONALD ISLANDS",
      "countryIso":"HM"
    },
    {
      "countryName":"HOLY SEE (VATICAN CITY STATE)",
      "countryIso":"VA"
    },
    {
      "countryName":"HONDURAS",
      "countryIso":"HN"
    },
    {
      "countryName":"HONG KONG",
      "countryIso":"HK"
    },
    {
      "countryName":"HUNGARY",
      "countryIso":"HU"
    },
    {
      "countryName":"ICELAND",
      "countryIso":"IS"
    },
    {
      "countryName":"INDIA",
      "countryIso":"IN"
    },
    {
      "countryName":"INDONESIA",
      "countryIso":"ID"
    },
    {
      "countryName":"IRAN, ISLAMIC REPUBLIC OF",
      "countryIso":"IR"
    },
    {
      "countryName":"IRAQ",
      "countryIso":"IQ"
    },
    {
      "countryName":"IRELAND",
      "countryIso":"IE"
    },
    {
      "countryName":"ISLE OF MAN",
      "countryIso":"IM"
    },
    {
      "countryName":"ISRAEL",
      "countryIso":"IL"
    },
    {
      "countryName":"ITALY",
      "countryIso":"IT"
    },
    {
      "countryName":"JAMAICA",
      "countryIso":"JM"
    },
    {
      "countryName":"JAPAN",
      "countryIso":"JP"
    },
    {
      "countryName":"JERSEY",
      "countryIso":"JE"
    },
    {
      "countryName":"JORDAN",
      "countryIso":"JO"
    },
    {
      "countryName":"KAZAKHSTAN",
      "countryIso":"KZ"
    },
    {
      "countryName":"KENYA",
      "countryIso":"KE"
    },
    {
      "countryName":"KIRIBATI",
      "countryIso":"KI"
    },
    {
      "countryName":"KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
      "countryIso":"KP"
    },
    {
      "countryName":"KOREA, REPUBLIC OF",
      "countryIso":"KR"
    },
    {
      "countryName":"KUWAIT",
      "countryIso":"KW"
    },
    {
      "countryName":"KYRGYZSTAN",
      "countryIso":"KG"
    },
    {
      "countryName":"LAO PEOPLE'S DEMOCRATIC REPUBLIC",
      "countryIso":"LA"
    },
    {
      "countryName":"LATVIA",
      "countryIso":"LV"
    },
    {
      "countryName":"LEBANON",
      "countryIso":"LB"
    },
    {
      "countryName":"LESOTHO",
      "countryIso":"LS"
    },
    {
      "countryName":"LIBERIA",
      "countryIso":"LR"
    },
    {
      "countryName":"LIBYA",
      "countryIso":"LY"
    },
    {
      "countryName":"LIECHTENSTEIN",
      "countryIso":"LI"
    },
    {
      "countryName":"LITHUANIA",
      "countryIso":"LT"
    },
    {
      "countryName":"LUXEMBOURG",
      "countryIso":"LU"
    },
    {
      "countryName":"MACAO",
      "countryIso":"MO"
    },
    {
      "countryName":"MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
      "countryIso":"MK"
    },
    {
      "countryName":"MADAGASCAR",
      "countryIso":"MG"
    },
    {
      "countryName":"MALAWI",
      "countryIso":"MW"
    },
    {
      "countryName":"MALAYSIA",
      "countryIso":"MY"
    },
    {
      "countryName":"MALDIVES",
      "countryIso":"MV"
    },
    {
      "countryName":"MALI",
      "countryIso":"ML"
    },
    {
      "countryName":"MALTA",
      "countryIso":"MT"
    },
    {
      "countryName":"MARSHALL ISLANDS",
      "countryIso":"MH"
    },
    {
      "countryName":"MARTINIQUE",
      "countryIso":"MQ"
    },
    {
      "countryName":"MAURITANIA",
      "countryIso":"MR"
    },
    {
      "countryName":"MAURITIUS",
      "countryIso":"MU"
    },
    {
      "countryName":"MAYOTTE",
      "countryIso":"YT"
    },
    {
      "countryName":"MEXICO",
      "countryIso":"MX"
    },
    {
      "countryName":"MICRONESIA, FEDERATED STATES OF",
      "countryIso":"FM"
    },
    {
      "countryName":"MOLDOVA, REPUBLIC OF",
      "countryIso":"MD"
    },
    {
      "countryName":"MONACO",
      "countryIso":"MC"
    },
    {
      "countryName":"MONGOLIA",
      "countryIso":"MN"
    },
    {
      "countryName":"MONTENEGRO",
      "countryIso":"ME"
    },
    {
      "countryName":"MONTSERRAT",
      "countryIso":"MS"
    },
    {
      "countryName":"MOROCCO",
      "countryIso":"MA"
    },
    {
      "countryName":"MOZAMBIQUE",
      "countryIso":"MZ"
    },
    {
      "countryName":"MYANMAR",
      "countryIso":"MM"
    },
    {
      "countryName":"NAMIBIA",
      "countryIso":"NA"
    },
    {
      "countryName":"NAURU",
      "countryIso":"NR"
    },
    {
      "countryName":"NEPAL",
      "countryIso":"NP"
    },
    {
      "countryName":"NETHERLANDS",
      "countryIso":"NL"
    },
    {
      "countryName":"NEW CALEDONIA",
      "countryIso":"NC"
    },
    {
      "countryName":"NEW ZEALAND",
      "countryIso":"NZ"
    },
    {
      "countryName":"NICARAGUA",
      "countryIso":"NI"
    },
    {
      "countryName":"NIGER",
      "countryIso":"NE"
    },
    {
      "countryName":"NIGERIA",
      "countryIso":"NG"
    },
    {
      "countryName":"NIUE",
      "countryIso":"NU"
    },
    {
      "countryName":"NORFOLK ISLAND",
      "countryIso":"NF"
    },
    {
      "countryName":"NORTHERN MARIANA ISLANDS",
      "countryIso":"MP"
    },
    {
      "countryName":"NORWAY",
      "countryIso":"NO"
    },
    {
      "countryName":"OMAN",
      "countryIso":"OM"
    },
    {
      "countryName":"PAKISTAN",
      "countryIso":"PK"
    },
    {
      "countryName":"PALAU",
      "countryIso":"PW"
    },
    {
      "countryName":"PALESTINE, STATE OF",
      "countryIso":"PS"
    },
    {
      "countryName":"PANAMA",
      "countryIso":"PA"
    },
    {
      "countryName":"PAPUA NEW GUINEA",
      "countryIso":"PG"
    },
    {
      "countryName":"PARAGUAY",
      "countryIso":"PY"
    },
    {
      "countryName":"PERU",
      "countryIso":"PE"
    },
    {
      "countryName":"PHILIPPINES",
      "countryIso":"PH"
    },
    {
      "countryName":"PITCAIRN",
      "countryIso":"PN"
    },
    {
      "countryName":"POLAND",
      "countryIso":"PL"
    },
    {
      "countryName":"PORTUGAL",
      "countryIso":"PT"
    },
    {
      "countryName":"PUERTO RICO",
      "countryIso":"PR"
    },
    {
      "countryName":"QATAR",
      "countryIso":"QA"
    },
    {
      "countryName":"RÉUNION",
      "countryIso":"RE"
    },
    {
      "countryName":"ROMANIA",
      "countryIso":"RO"
    },
    {
      "countryName":"RUSSIAN FEDERATION",
      "countryIso":"RU"
    },
    {
      "countryName":"RWANDA",
      "countryIso":"RW"
    },
    {
      "countryName":"SAINT BARTHÉLEMY",
      "countryIso":"BL"
    },
    {
      "countryName":"SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA",
      "countryIso":"SH"
    },
    {
      "countryName":"SAINT KITTS AND NEVIS",
      "countryIso":"KN"
    },
    {
      "countryName":"SAINT LUCIA",
      "countryIso":"LC"
    },
    {
      "countryName":"SAINT MARTIN (FRENCH PART)",
      "countryIso":"MF"
    },
    {
      "countryName":"SAINT PIERRE AND MIQUELON",
      "countryIso":"PM"
    },
    {
      "countryName":"SAINT VINCENT AND THE GRENADINES",
      "countryIso":"VC"
    },
    {
      "countryName":"SAMOA",
      "countryIso":"WS"
    },
    {
      "countryName":"SAN MARINO",
      "countryIso":"SM"
    },
    {
      "countryName":"SAO TOME AND PRINCIPE",
      "countryIso":"ST"
    },
    {
      "countryName":"SAUDI ARABIA",
      "countryIso":"SA"
    },
    {
      "countryName":"SENEGAL",
      "countryIso":"SN"
    },
    {
      "countryName":"SERBIA",
      "countryIso":"RS"
    },
    {
      "countryName":"SEYCHELLES",
      "countryIso":"SC"
    },
    {
      "countryName":"SIERRA LEONE",
      "countryIso":"SL"
    },
    {
      "countryName":"SINGAPORE",
      "countryIso":"SG"
    },
    {
      "countryName":"SINT MAARTEN (DUTCH PART)",
      "countryIso":"SX"
    },
    {
      "countryName":"SLOVAKIA",
      "countryIso":"SK"
    },
    {
      "countryName":"SLOVENIA",
      "countryIso":"SI"
    },
    {
      "countryName":"SOLOMON ISLANDS",
      "countryIso":"SB"
    },
    {
      "countryName":"SOMALIA",
      "countryIso":"SO"
    },
    {
      "countryName":"SOUTH AFRICA",
      "countryIso":"ZA"
    },
    {
      "countryName":"SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
      "countryIso":"GS"
    },
    {
      "countryName":"SOUTH SUDAN",
      "countryIso":"SS"
    },
    {
      "countryName":"SPAIN",
      "countryIso":"ES"
    },
    {
      "countryName":"SRI LANKA",
      "countryIso":"LK"
    },
    {
      "countryName":"SUDAN",
      "countryIso":"SD"
    },
    {
      "countryName":"SURINAME",
      "countryIso":"SR"
    },
    {
      "countryName":"SVALBARD AND JAN MAYEN",
      "countryIso":"SJ"
    },
    {
      "countryName":"SWAZILAND",
      "countryIso":"SZ"
    },
    {
      "countryName":"SWEDEN",
      "countryIso":"SE"
    },
    {
      "countryName":"SWITZERLAND",
      "countryIso":"CH"
    },
    {
      "countryName":"SYRIAN ARAB REPUBLIC",
      "countryIso":"SY"
    },
    {
      "countryName":"TAIWAN, PROVINCE OF CHINA",
      "countryIso":"TW"
    },
    {
      "countryName":"TAJIKISTAN",
      "countryIso":"TJ"
    },
    {
      "countryName":"TANZANIA, UNITED REPUBLIC OF",
      "countryIso":"TZ"
    },
    {
      "countryName":"THAILAND",
      "countryIso":"TH"
    },
    {
      "countryName":"TIMOR-LESTE",
      "countryIso":"TL"
    },
    {
      "countryName":"TOGO",
      "countryIso":"TG"
    },
    {
      "countryName":"TOKELAU",
      "countryIso":"TK"
    },
    {
      "countryName":"TONGA",
      "countryIso":"TO"
    },
    {
      "countryName":"TRINIDAD AND TOBAGO",
      "countryIso":"TT"
    },
    {
      "countryName":"TUNISIA",
      "countryIso":"TN"
    },
    {
      "countryName":"TURKEY",
      "countryIso":"TR"
    },
    {
      "countryName":"TURKMENISTAN",
      "countryIso":"TM"
    },
    {
      "countryName":"TURKS AND CAICOS ISLANDS",
      "countryIso":"TC"
    },
    {
      "countryName":"TUVALU",
      "countryIso":"TV"
    },
    {
      "countryName":"UGANDA",
      "countryIso":"UG"
    },
    {
      "countryName":"UKRAINE",
      "countryIso":"UA"
    },
    {
      "countryName":"UNITED ARAB EMIRATES",
      "countryIso":"AE"
    },
    {
      "countryName":"UNITED KINGDOM",
      "countryIso":"GB"
    },
    {
      "countryName":"UNITED STATES",
      "countryIso":"US"
    },
    {
      "countryName":"UNITED STATES MINOR OUTLYING ISLANDS",
      "countryIso":"UM"
    },
    {
      "countryName":"URUGUAY",
      "countryIso":"UY"
    },
    {
      "countryName":"UZBEKISTAN",
      "countryIso":"UZ"
    },
    {
      "countryName":"VANUATU",
      "countryIso":"VU"
    },
    {
      "countryName":"VENEZUELA, BOLIVARIAN REPUBLIC OF",
      "countryIso":"VE"
    },
    {
      "countryName":"VIET NAM",
      "countryIso":"VN"
    },
    {
      "countryName":"VIRGIN ISLANDS, BRITISH",
      "countryIso":"VG"
    },
    {
      "countryName":"VIRGIN ISLANDS, U.S.",
      "countryIso":"VI"
    },
    {
      "countryName":"WALLIS AND FUTUNA",
      "countryIso":"WF"
    },
    {
      "countryName":"WESTERN SAHARA",
      "countryIso":"EH"
    },
    {
      "countryName":"YEMEN",
      "countryIso":"YE"
    },
    {
      "countryName":"ZAMBIA",
      "countryIso":"ZM"
    },
    {
      "countryName":"ZIMBABWE",
      "countryIso":"ZW"
    }
  ]
 });